[package]
name = "auth-rs"
version = "0.1.0"
authors = ["Gabriel Araújo <gabriel140492@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
diesel = { version = "1.4.1", features = ["postgres"] }
url = "1.7.2"
